[package]
name = "trilogy_save_editor"
version = "0.1.0"
authors = ["Karlitos <ke0opt4cq@relay.firefox.com>"]
license = "CeCILL-2.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = true

[dependencies]
# Macro
save_data_derive = { path = "save_data_derive" }
# Windows
winapi = { version = "0.3", features = ["consoleapi", "wincon"], default-features = false }
wfd = "0.1"
# Std-like
anyhow = "1.0"
bitvec = { version = "0.22", features = ["std"], default-features = false }
indexmap = { version = "1.6", features = ["std"], default-features = false }
encoding_rs = { version = "0.8", default-features = false }
num-traits = "0.2"
num-derive = "0.3"
# Async
async-trait = "0.1"
tokio = { version = "1.0", features = [
    "rt-multi-thread",
    "sync",
    "parking_lot",
    "macros",
    "fs",
    "io-util",
], default-features = false }
# Sync
# parking_lot = "0.11"
flume = { version = "0.10", features = ["async"], default-features = false }
# Utils
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"], default-features = false }
bincode = "1.3"
crc = "2.0.0-rc.1"
zip = { version = "0.5", features = ["deflate-miniz"], default-features = false }
# Dear ImGui
imgui = { git = "https://github.com/imgui-rs/imgui-rs" }
imgui-glium-renderer = { git = "https://github.com/imgui-rs/imgui-rs" }
imgui-winit-support = { git = "https://github.com/imgui-rs/imgui-rs" }
glium = "0.29"
clipboard = "0.5"
